site_name: MFX Academy
theme:
  name: material
  custom_dir: overrides
  highlightjs: true
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - search.suggest
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.select
    - content.code.copy


  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep-purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep-purple


repo_name: grupomfx/imersao-back-end-academy
repo_url: https://github.com/grupomfx/imersao-back-end-academy

nav:
  - Home: index.md
  - Ementa: ementa.md
  - Conteudos:
      - Sessao 01: sessao_one.md
      - Sessão 02: sessao_two.md  
  - Projetos:
    - Projeto 01: projeto_one.md


extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/grupomfx

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mfxtechnologymadesimple/

    - icon: fontawesome/brands/discord
      link: https://discord.gg/kQqgSyMD

